"""evaluations score sheets overrides

Revision ID: 1a097e550877
Revises: f2078ea32f3f
Create Date: 2026-09-03 01:55:54.722543+05:30
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1a097e550877"
down_revision: str | None = "f2078ea32f3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "late_policy",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("scope_id", sa.Integer(), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "scope_id", "version", name="uq_late_policy_scope"),
    )
    op.create_table(
        "evaluation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("submission_version", sa.Integer(), nullable=False),
        sa.Column("rubric_id", sa.Integer(), nullable=False),
        sa.Column("rubric_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "engine",
            sa.Enum(
                "MANUAL", "AI", name="evaluationengine", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETE",
                "FAILED",
                name="evaluationstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(length=120), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("graph_version", sa.String(length=32), nullable=True),
        sa.Column("raw_response", sa.JSON(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.email"],
        ),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["rubric.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "version", name="uq_evaluation_version"),
    )
    with op.batch_alter_table("evaluation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evaluation_rubric_id"), ["rubric_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evaluation_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "criterion_score",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("criterion_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "FOLLOWED",
                "PARTIAL",
                "NOT_FOLLOWED",
                "NO_EVIDENCE",
                name="verdict",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("evidence_span", sa.Text(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criterion_id"],
            ["criterion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_id", "criterion_id", name="uq_criterion_score"),
    )
    with op.batch_alter_table("criterion_score", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_criterion_score_criterion_id"), ["criterion_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_criterion_score_evaluation_id"),
            ["evaluation_id"],
            unique=False,
        )

    op.create_table(
        "score_sheet",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("max_marks", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("weighted_percent", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("base_total", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("penalty", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("final_total", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("days_late", sa.Integer(), nullable=False),
        sa.Column(
            "attendance_status",
            sa.Enum(
                "PRESENT",
                "LATE",
                "ABSENT",
                "REINSTATED",
                name="attendancestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("reinstated", sa.Boolean(), nullable=False),
        sa.Column("reinstate_reason", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.String(length=320), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("faculty_note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.email"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_id", name="uq_score_sheet_evaluation"),
    )
    with op.batch_alter_table("score_sheet", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_score_sheet_evaluation_id"), ["evaluation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_score_sheet_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "score_override",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("score_sheet_id", sa.Integer(), nullable=False),
        sa.Column("criterion_id", sa.Integer(), nullable=False),
        sa.Column("old_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("new_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "old_verdict",
            sa.Enum(
                "FOLLOWED",
                "PARTIAL",
                "NOT_FOLLOWED",
                "NO_EVIDENCE",
                name="verdict",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column(
            "new_verdict",
            sa.Enum(
                "FOLLOWED",
                "PARTIAL",
                "NOT_FOLLOWED",
                "NO_EVIDENCE",
                name="verdict",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("overridden_by", sa.String(length=320), nullable=False),
        sa.Column(
            "overridden_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["criterion_id"],
            ["criterion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["overridden_by"],
            ["users.email"],
        ),
        sa.ForeignKeyConstraint(
            ["score_sheet_id"],
            ["score_sheet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("score_override", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_score_override_score_sheet_id"),
            ["score_sheet_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score_override", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_override_score_sheet_id"))

    op.drop_table("score_override")
    with op.batch_alter_table("score_sheet", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_sheet_submission_id"))
        batch_op.drop_index(batch_op.f("ix_score_sheet_evaluation_id"))

    op.drop_table("score_sheet")
    with op.batch_alter_table("criterion_score", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_criterion_score_evaluation_id"))
        batch_op.drop_index(batch_op.f("ix_criterion_score_criterion_id"))

    op.drop_table("criterion_score")
    with op.batch_alter_table("evaluation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluation_submission_id"))
        batch_op.drop_index(batch_op.f("ix_evaluation_rubric_id"))

    op.drop_table("evaluation")
    op.drop_table("late_policy")
    # ### end Alembic commands ###
