"""rubrics criteria submissions

Revision ID: f2078ea32f3f
Revises: c0f87d7871b0
Create Date: 2026-09-03 01:07:51.043975+05:30
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f2078ea32f3f"
down_revision: str | None = "c0f87d7871b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rubric",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("milestone_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.String(length=320), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["review_milestone.id"],
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "milestone_id", "version", name="uq_rubric_milestone_version"
        ),
    )
    with op.batch_alter_table("rubric", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rubric_milestone_id"), ["milestone_id"], unique=False
        )

    op.create_table(
        "submission",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("milestone_id", sa.Integer(), nullable=False),
        sa.Column("student_email", sa.String(length=320), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SUBMITTED",
                "SUPERSEDED",
                name="submissionstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("text_extract", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["review_milestone.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_email"],
            ["users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "milestone_id",
            "student_email",
            "version",
            name="uq_submission_student_version",
        ),
    )
    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submission_milestone_id"), ["milestone_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_submission_student_email"), ["student_email"], unique=False
        )

    op.create_table(
        "criterion",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rubric_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("expected_evidence", sa.Text(), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["rubric.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rubric_id", "code", name="uq_criterion_code"),
    )
    with op.batch_alter_table("criterion", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_criterion_rubric_id"), ["rubric_id"], unique=False
        )

    op.create_table(
        "submission_file",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("stored_path", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("extracted_chars", sa.Integer(), nullable=False),
        sa.Column("extract_note", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("submission_file", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submission_file_submission_id"),
            ["submission_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_file_submission_id"))

    op.drop_table("submission_file")
    with op.batch_alter_table("criterion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_criterion_rubric_id"))

    op.drop_table("criterion")
    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_student_email"))
        batch_op.drop_index(batch_op.f("ix_submission_milestone_id"))

    op.drop_table("submission")
    with op.batch_alter_table("rubric", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rubric_milestone_id"))

    op.drop_table("rubric")
    # ### end Alembic commands ###
