"""subjects enrollment cycles milestones

Revision ID: c0f87d7871b0
Revises: 4c5ce39a003b
Create Date: 2026-09-02 19:42:20.551671+05:30
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c0f87d7871b0"
down_revision: str | None = "4c5ce39a003b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subject",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("semester", sa.Integer(), nullable=False),
        sa.Column("owner_email", sa.String(length=320), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_email"],
            ["users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "semester", name="uq_subject_code_sem"),
    )
    with op.batch_alter_table("subject", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subject_code"), ["code"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_subject_owner_email"), ["owner_email"], unique=False
        )

    op.create_table(
        "enrollment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_email", sa.String(length=320), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("batch", sa.String(length=32), nullable=True),
        sa.Column("group_label", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_email"],
            ["users.email"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_email", "subject_id", name="uq_enrollment_student"),
    )
    with op.batch_alter_table("enrollment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_enrollment_student_email"), ["student_email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_enrollment_subject_id"), ["subject_id"], unique=False
        )

    op.create_table(
        "project_cycle",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("academic_year", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subject.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_cycle", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_cycle_subject_id"), ["subject_id"], unique=False
        )

    op.create_table(
        "review_milestone",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_marks", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["project_cycle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cycle_id", "index", name="uq_milestone_cycle_index"),
    )
    with op.batch_alter_table("review_milestone", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_milestone_cycle_id"), ["cycle_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_milestone", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_milestone_cycle_id"))

    op.drop_table("review_milestone")
    with op.batch_alter_table("project_cycle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_cycle_subject_id"))

    op.drop_table("project_cycle")
    with op.batch_alter_table("enrollment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enrollment_subject_id"))
        batch_op.drop_index(batch_op.f("ix_enrollment_student_email"))

    op.drop_table("enrollment")
    with op.batch_alter_table("subject", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subject_owner_email"))
        batch_op.drop_index(batch_op.f("ix_subject_code"))

    op.drop_table("subject")
    # ### end Alembic commands ###
