"""member adjustments for group contribution

Revision ID: 1a98d1247246
Revises: 07a3be0a5f62
Create Date: 2026-09-05 00:06:21.009085+05:30
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1a98d1247246"
down_revision: str | None = "07a3be0a5f62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_adjustment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("score_sheet_id", sa.Integer(), nullable=False),
        sa.Column("student_email", sa.String(length=320), nullable=False),
        sa.Column("delta", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("adjusted_by", sa.String(length=320), nullable=False),
        sa.Column(
            "adjusted_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["adjusted_by"],
            ["users.email"],
        ),
        sa.ForeignKeyConstraint(
            ["score_sheet_id"],
            ["score_sheet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_email"],
            ["users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("member_adjustment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_member_adjustment_score_sheet_id"),
            ["score_sheet_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_member_adjustment_student_email"),
            ["student_email"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("member_adjustment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_member_adjustment_student_email"))
        batch_op.drop_index(batch_op.f("ix_member_adjustment_score_sheet_id"))

    op.drop_table("member_adjustment")
    # ### end Alembic commands ###
