"""student queries and public notes

Revision ID: 0f204ef72ce4
Revises: 1a097e550877
Create Date: 2026-09-03 11:10:55.609971+05:30
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0f204ef72ce4"
down_revision: str | None = "1a097e550877"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_query",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_email", sa.String(length=320), nullable=False),
        sa.Column("milestone_id", sa.Integer(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("ai_answer", sa.Text(), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column("faculty_reply", sa.Text(), nullable=True),
        sa.Column("replied_by", sa.String(length=320), nullable=True),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["review_milestone.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replied_by"],
            ["users.email"],
        ),
        sa.ForeignKeyConstraint(
            ["student_email"],
            ["users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("student_query", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_query_milestone_id"), ["milestone_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_query_student_email"), ["student_email"], unique=False
        )

    with op.batch_alter_table("review_milestone", schema=None) as batch_op:
        batch_op.add_column(sa.Column("public_notes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_milestone", schema=None) as batch_op:
        batch_op.drop_column("public_notes")

    with op.batch_alter_table("student_query", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_query_student_email"))
        batch_op.drop_index(batch_op.f("ix_student_query_milestone_id"))

    op.drop_table("student_query")
    # ### end Alembic commands ###
