"""project groups, github profiles, submission links

Revision ID: 07a3be0a5f62
Revises: 0f204ef72ce4
Create Date: 2026-09-04 10:17:32.979491+05:30
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "07a3be0a5f62"
down_revision: str | None = "0f204ef72ce4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_submission_group_id"), ["group_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_submission_group", "project_group", ["group_id"], ["id"]
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("github_username", sa.String(length=39), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("github_username")

    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.drop_constraint("fk_submission_group", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_submission_group_id"))
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###
